sudo: required
language: node_js

services:
    - docker

before_install:
    # build docker container with dev config for lezu-client
    - docker build -t vvahe/lezu-client-test -f ./client/Dockerfile.dev ./client

script:
    # run test for lezu-client
    - docker run vvahe/lezu-client-test npm run ci-test -- --coverage

after_success:
    # create production images
    - docker build -t vvahe/lezu_client ./client
    - docker build -t vvahe/lezu_api ./api
    - docker build -t vvahe/lezu_nginx ./nginx
    # login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    # push images to docker hub
    - docker push vvahe/lezu_client
    - docker push vvahe/lezu_api
    - docker push vvahe/lezu_nginx

deploy:
    provider: elasticbeanstalk
    region: eu-west-2
    app: Lezu
    env: Lezu-env
    bucket_name: elasticbeanstalk-eu-west-2-322210610177
    bucket_path: lezu
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: '$AWS_SECRET_KEY'
