version: '3.7'

services:
    db:
        restart: always
        image: 'mysql:5.7.27'
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=word_trainer
        volumes:
            - ./api/db_scripts/:/docker-entrypoint-initdb.d/

    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./api
        restart: always
        volumes:
            - /app/node_modules # leave node modules folder as is
            - ./api:/app # copy content from server folder to /app (WORKDIR)d
        depends_on:
            - db
        environment:
            - SECRET_OR_KEY=secret
            - MYSQL_HOST=db
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=word_trainer

    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        restart: always
        volumes:
            - /app/node_modules
            - ./client:/app
        depends_on:
            - db
            - api

    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '4000:80'
