version: '3.7'

services:
    db:
        container_name: lezu_db
        restart: always
        image: 'mysql:5.7.27'
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=lezu_db
        volumes:
            - ./api/db_scripts/:/docker-entrypoint-initdb.d/

    api:
        container_name: lezu_api
        build:
            dockerfile: Dockerfile.dev
            context: ./api
        restart: always
        volumes:
            - /app/node_modules # leave node modules folder as is
            - ./api:/app # copy content from server folder to /app (WORKDIR)
        depends_on:
            - db
        environment:
            - SECRET_OR_KEY=secret
            - MYSQL_HOST=db
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=lezu_db

    client:
        container_name: lezu_client
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        restart: always
        volumes:
            - /app/node_modules # leave node modules folder as is
            - ./client:/app # copy content from server folder to /app (WORKDIR)
        depends_on:
            - db
            - api

    nginx:
        container_name: lezu_nginx
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '4000:80' # map host port 4000 to nginx container port 80
