FROM nginx

COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./keys/lezu_private_key.key /etc/nginx/certs/lezu/lezu_private_key.key
COPY ./keys/lezu_ssl_certificate.cer /etc/nginx/certs/lezu/lezu_ssl_certificate.cer